# Generated by Django 4.0.6 on 2022-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('electronic', models.CharField(max_length=30)),
                ('items', models.CharField(max_length=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
